module.exports = {
  pad: require('./src/pad'),
  error: require('./src/error'),
  alertAdmins: require('./src/alertAdmins'),
  handlerLoader: require('./src/handlerLoader'),
  verifyCooldown: require('./src/verifyCooldown'),
  verifyActive: require('./src/verifyActive'),
  moreSimilar: require('./src/moreSimilar'),
  levenshteinDistance: require('./src/levenshteinDistance'),
  logger: require('./src/logger'),
  loadCommands: require('./src/loadCommands'),
  isEquivalent: require('./src/isEquivalent'),
  getLevel: require('./src/getLevel'),
  verifyActiveCooldown: require('./src/verifyActiveCooldown'),
  genFakeMessage: require('./src/genFakeMessage'),
  genHtmlMessage: require('./src/genHtmlMessage'),
  sendHtmlDoc: require('./src/sendHtmlDoc'),
  generateToken: require('./src/generateToken'),
  pathToObject: require('./src/pathToObject'),
  checkKeys: require('./src/checkKeys')
};